// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_fWfSJwByUp4IvWYWZwy2dP7oip3Qfio',
    appId: '1:312627029897:web:c398279ddc74d48b892358',
    messagingSenderId: '312627029897',
    projectId: 'higop-mcommerce',
    authDomain: 'higop-mcommerce.firebaseapp.com',
    storageBucket: 'higop-mcommerce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE012Te28UkUDSY89gHQrTVTJXGBwh2DY',
    appId: '1:312627029897:android:2ee3e67aa1901e03892358',
    messagingSenderId: '312627029897',
    projectId: 'higop-mcommerce',
    storageBucket: 'higop-mcommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeMFwnQAJMq4bXwWXHmza4dQ2y5IjrsaM',
    appId: '1:312627029897:ios:41661abab93bf4d3892358',
    messagingSenderId: '312627029897',
    projectId: 'higop-mcommerce',
    storageBucket: 'higop-mcommerce.firebasestorage.app',
    iosBundleId: 'com.example.mcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeMFwnQAJMq4bXwWXHmza4dQ2y5IjrsaM',
    appId: '1:312627029897:ios:41661abab93bf4d3892358',
    messagingSenderId: '312627029897',
    projectId: 'higop-mcommerce',
    storageBucket: 'higop-mcommerce.firebasestorage.app',
    iosBundleId: 'com.example.mcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_fWfSJwByUp4IvWYWZwy2dP7oip3Qfio',
    appId: '1:312627029897:web:0f2a9bb4e7abf3a9892358',
    messagingSenderId: '312627029897',
    projectId: 'higop-mcommerce',
    authDomain: 'higop-mcommerce.firebaseapp.com',
    storageBucket: 'higop-mcommerce.firebasestorage.app',
  );
}
